# Generated by Django 4.2 on 2023-05-06 20:17

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Professional Club Name", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Professional Club Names",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of Company or College", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company",
            },
        ),
        migrations.CreateModel(
            name="Expertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Midfield",
                        help_text="Attack, Midfield, Defence or Goalkeeping",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Expertise",
            },
        ),
        migrations.CreateModel(
            name="FieldPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Field Position", max_length=100)),
            ],
            options={
                "verbose_name_plural": "Field Position",
            },
        ),
        migrations.CreateModel(
            name="Foot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Preferred Foot", max_length=10)),
            ],
            options={
                "verbose_name_plural": "Preferred Foot",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Professional Player Name", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Professional Player Names",
            },
        ),
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of Profession", max_length=100),
                ),
            ],
            options={
                "verbose_name_plural": "Profession",
            },
        ),
        migrations.CreateModel(
            name="MemberList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Name of Member", max_length=100)),
                ("image", models.ImageField(upload_to="upload/")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Phone number with country code",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "pune_address",
                    models.TextField(
                        help_text="Pune Address of Member", max_length=300
                    ),
                ),
                (
                    "kolhapur_address",
                    models.TextField(
                        help_text="Kolhapur Address of Member", max_length=300
                    ),
                ),
                ("birthdate", models.DateField(help_text="Birth date of the member")),
                (
                    "area_of_expertise",
                    models.ForeignKey(
                        help_text="Attack, Medfield, Defence or Goalkeeping",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_of_expertise",
                        to="members.expertise",
                    ),
                ),
                (
                    "current_company",
                    models.ForeignKey(
                        help_text="Profession",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.company",
                    ),
                ),
                (
                    "favorite_club",
                    models.ForeignKey(
                        help_text="Favorite Club",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.club",
                    ),
                ),
                (
                    "favorite_player",
                    models.ForeignKey(
                        help_text="Favorite Player",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.player",
                    ),
                ),
                (
                    "preferred_field_position",
                    models.ForeignKey(
                        help_text="Preferred field position",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_field_position",
                        to="members.fieldposition",
                    ),
                ),
                (
                    "preferred_foot",
                    models.ForeignKey(
                        help_text="Preferred Foot",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_foot",
                        to="members.foot",
                    ),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        help_text="Profession",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.profession",
                    ),
                ),
                (
                    "secondary_field_position",
                    models.ForeignKey(
                        help_text="Secondary field position",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_field_position",
                        to="members.fieldposition",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "KBFC Member List",
            },
        ),
    ]
