# Generated by Django 4.2 on 2023-05-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberlist",
            name="image",
            field=models.ImageField(upload_to="static/upload/"),
        ),
    ]
