# Generated by Django 4.2 on 2023-05-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_alter_memberlist_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberlist",
            name="image",
            field=models.ImageField(upload_to="upload/"),
        ),
    ]
