# Generated by Django 4.2 on 2023-04-30 00:10

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Name of Venue", max_length=100)),
                ("address", models.TextField(help_text="Address of Venue")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Phone number with country code",
                        max_length=128,
                        region=None,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Venue",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Name of event", max_length=100)),
                (
                    "description",
                    models.CharField(
                        help_text="Description of the event", max_length=300
                    ),
                ),
                ("date", models.DateField(help_text="Date of the event.")),
                ("time", models.TimeField(help_text="Time of the event.")),
                (
                    "event_duration",
                    models.SmallIntegerField(help_text="Duration of the Event"),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        help_text="Venue of the event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue",
                        to="events.venue",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Event",
            },
        ),
    ]
