# Generated by Django 4.2 on 2023-04-30 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name_plural": "Events"},
        ),
    ]
