# Generated by Django 4.2 on 2023-04-15 19:34

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Professional Club Name", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Club Names",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of Company or College", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company",
            },
        ),
        migrations.CreateModel(
            name="FieldPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Field Position", max_length=100)),
            ],
            options={
                "verbose_name_plural": "Field Position",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Professional Player Name", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Professional Player Names",
            },
        ),
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of Profession", max_length=100),
                ),
            ],
            options={
                "verbose_name_plural": "Profession",
            },
        ),
        migrations.CreateModel(
            name="MemberList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Name of Member", max_length=100)),
                ("image", models.ImageField(upload_to="upload/")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Phone number with country code",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "pune_address",
                    models.TextField(
                        help_text="Pune Address of Member", max_length=300
                    ),
                ),
                (
                    "kolhapur_address",
                    models.TextField(
                        help_text="Kolhapur Address of Member", max_length=300
                    ),
                ),
                (
                    "birthdate",
                    models.DateTimeField(help_text="Birth date of the member"),
                ),
                (
                    "current_company",
                    models.ForeignKey(
                        help_text="Profession",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.company",
                    ),
                ),
                (
                    "favorite_club",
                    models.ForeignKey(
                        help_text="Favorite Club",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.club",
                    ),
                ),
                (
                    "favorite_player",
                    models.ForeignKey(
                        help_text="Favorite Player",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.player",
                    ),
                ),
                (
                    "preferred_field_position",
                    models.ForeignKey(
                        help_text="Preferred field position",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_field_position",
                        to="member.fieldposition",
                    ),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        help_text="Profession",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.profession",
                    ),
                ),
                (
                    "secondary_field_position",
                    models.ForeignKey(
                        help_text="Secondary field position",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_field_position",
                        to="member.fieldposition",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "KBFC Member List",
            },
        ),
    ]
