# Generated by Django 4.2 on 2023-04-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={"verbose_name_plural": "Professional Club Names"},
        ),
        migrations.AlterField(
            model_name="memberlist",
            name="birthdate",
            field=models.DateField(help_text="Birth date of the member"),
        ),
    ]
